//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class DirectArrayFbxVector2 : FbxLayerElementArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DirectArrayFbxVector2(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.DirectArrayFbxVector2_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectArrayFbxVector2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DirectArrayFbxVector2() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_DirectArrayFbxVector2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DirectArrayFbxVector2(EFbxType pDataType) : this(fbx_wrapperPINVOKE.new_DirectArrayFbxVector2((int)pDataType), true) {
  }

  public int Add(FbxVector2 pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_Add(swigCPtr, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int InsertAt(int pIndex, FbxVector2 pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_InsertAt(swigCPtr, pIndex, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAt(int pIndex, FbxVector2 pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxVector2_SetAt(swigCPtr, pIndex, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetLast(FbxVector2 pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxVector2_SetLast(swigCPtr, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector2 RemoveAt(int pIndex) {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_RemoveAt(swigCPtr, pIndex), true);
    return ret;
  }

  public FbxVector2 RemoveLast() {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_RemoveLast(swigCPtr), true);
    return ret;
  }

  public bool RemoveIt(FbxVector2 pItem) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_RemoveIt(swigCPtr, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector2 GetAt(int pIndex) {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_GetAt(swigCPtr, pIndex), true);
    return ret;
  }

  public FbxVector2 GetFirst() {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_GetFirst(swigCPtr), true);
    return ret;
  }

  public FbxVector2 GetLast() {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_GetLast(swigCPtr), true);
    return ret;
  }

  public int Find(FbxVector2 pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_Find(swigCPtr, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int FindAfter(int pAfterIndex, FbxVector2 pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_FindAfter(swigCPtr, pAfterIndex, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int FindBefore(int pBeforeIndex, FbxVector2 pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVector2_FindBefore(swigCPtr, pBeforeIndex, FbxVector2.getCPtr(pItem));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector2 at(int pIndex) {
    FbxVector2 ret = new FbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_at(swigCPtr, pIndex), true);
    return ret;
  }

  public FbxLayerElementArray assign(SWIGTYPE_p_FbxArrayT_FbxVector2_t pArrayTemplate) {
    FbxLayerElementArray ret = new FbxLayerElementArray(fbx_wrapperPINVOKE.DirectArrayFbxVector2_assign__SWIG_0(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxVector2_t.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DirectArrayFbxVector2 assign(DirectArrayFbxVector2 pArrayTemplate) {
    DirectArrayFbxVector2 ret = new DirectArrayFbxVector2(fbx_wrapperPINVOKE.DirectArrayFbxVector2_assign__SWIG_1(swigCPtr, DirectArrayFbxVector2.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
