//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class DirectArrayFbxBool : FbxLayerElementArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DirectArrayFbxBool(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.DirectArrayFbxBool_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectArrayFbxBool obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DirectArrayFbxBool() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_DirectArrayFbxBool(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DirectArrayFbxBool(EFbxType pDataType) : this(fbx_wrapperPINVOKE.new_DirectArrayFbxBool((int)pDataType), true) {
  }

  public int Add(bool pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_Add(swigCPtr, pItem);
    return ret;
  }

  public int InsertAt(int pIndex, bool pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_InsertAt(swigCPtr, pIndex, pItem);
    return ret;
  }

  public void SetAt(int pIndex, bool pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxBool_SetAt(swigCPtr, pIndex, pItem);
  }

  public void SetLast(bool pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxBool_SetLast(swigCPtr, pItem);
  }

  public bool RemoveAt(int pIndex) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_RemoveAt(swigCPtr, pIndex);
    return ret;
  }

  public bool RemoveLast() {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_RemoveLast(swigCPtr);
    return ret;
  }

  public bool RemoveIt(bool pItem) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_RemoveIt(swigCPtr, pItem);
    return ret;
  }

  public bool GetAt(int pIndex) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_GetAt(swigCPtr, pIndex);
    return ret;
  }

  public bool GetFirst() {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_GetFirst(swigCPtr);
    return ret;
  }

  public bool GetLast() {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_GetLast(swigCPtr);
    return ret;
  }

  public int Find(bool pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_Find(swigCPtr, pItem);
    return ret;
  }

  public int FindAfter(int pAfterIndex, bool pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_FindAfter(swigCPtr, pAfterIndex, pItem);
    return ret;
  }

  public int FindBefore(int pBeforeIndex, bool pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_FindBefore(swigCPtr, pBeforeIndex, pItem);
    return ret;
  }

  public bool at(int pIndex) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxBool_at(swigCPtr, pIndex);
    return ret;
  }

  public FbxLayerElementArray assign(SWIGTYPE_p_FbxArrayT_bool_t pArrayTemplate) {
    FbxLayerElementArray ret = new FbxLayerElementArray(fbx_wrapperPINVOKE.DirectArrayFbxBool_assign__SWIG_0(swigCPtr, SWIGTYPE_p_FbxArrayT_bool_t.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DirectArrayFbxBool assign(DirectArrayFbxBool pArrayTemplate) {
    DirectArrayFbxBool ret = new DirectArrayFbxBool(fbx_wrapperPINVOKE.DirectArrayFbxBool_assign__SWIG_1(swigCPtr, DirectArrayFbxBool.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
