//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class DirectArrayFbxTexturePtr : FbxLayerElementArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DirectArrayFbxTexturePtr(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectArrayFbxTexturePtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DirectArrayFbxTexturePtr() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_DirectArrayFbxTexturePtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DirectArrayFbxTexturePtr(EFbxType pDataType) : this(fbx_wrapperPINVOKE.new_DirectArrayFbxTexturePtr((int)pDataType), true) {
  }

  public int Add(FbxTexture pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_Add(swigCPtr, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public int InsertAt(int pIndex, FbxTexture pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_InsertAt(swigCPtr, pIndex, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public void SetAt(int pIndex, FbxTexture pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_SetAt(swigCPtr, pIndex, FbxTexture.getCPtr(pItem));
  }

  public void SetLast(FbxTexture pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_SetLast(swigCPtr, FbxTexture.getCPtr(pItem));
  }

  public FbxTexture RemoveAt(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_RemoveAt(swigCPtr, pIndex);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public FbxTexture RemoveLast() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_RemoveLast(swigCPtr);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public bool RemoveIt(FbxTexture pItem) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_RemoveIt(swigCPtr, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public FbxTexture GetAt(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_GetAt(swigCPtr, pIndex);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public FbxTexture GetFirst() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_GetFirst(swigCPtr);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public FbxTexture GetLast() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_GetLast(swigCPtr);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public int Find(FbxTexture pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_Find(swigCPtr, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public int FindAfter(int pAfterIndex, FbxTexture pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_FindAfter(swigCPtr, pAfterIndex, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public int FindBefore(int pBeforeIndex, FbxTexture pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_FindBefore(swigCPtr, pBeforeIndex, FbxTexture.getCPtr(pItem));
    return ret;
  }

  public FbxTexture at(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_at(swigCPtr, pIndex);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public FbxLayerElementArray assign(SWIGTYPE_p_FbxArrayT_FbxTexture_p_t pArrayTemplate) {
    FbxLayerElementArray ret = new FbxLayerElementArray(fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_assign__SWIG_0(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxTexture_p_t.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DirectArrayFbxTexturePtr assign(DirectArrayFbxTexturePtr pArrayTemplate) {
    DirectArrayFbxTexturePtr ret = new DirectArrayFbxTexturePtr(fbx_wrapperPINVOKE.DirectArrayFbxTexturePtr_assign__SWIG_1(swigCPtr, DirectArrayFbxTexturePtr.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
