//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class DirectArrayFbxVoidPtr : FbxLayerElementArray {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DirectArrayFbxVoidPtr(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectArrayFbxVoidPtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DirectArrayFbxVoidPtr() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_DirectArrayFbxVoidPtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DirectArrayFbxVoidPtr(EFbxType pDataType) : this(fbx_wrapperPINVOKE.new_DirectArrayFbxVoidPtr((int)pDataType), true) {
  }

  public int Add(SWIGTYPE_p_void pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_Add(swigCPtr, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public int InsertAt(int pIndex, SWIGTYPE_p_void pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_InsertAt(swigCPtr, pIndex, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public void SetAt(int pIndex, SWIGTYPE_p_void pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_SetAt(swigCPtr, pIndex, SWIGTYPE_p_void.getCPtr(pItem));
  }

  public void SetLast(SWIGTYPE_p_void pItem) {
    fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_SetLast(swigCPtr, SWIGTYPE_p_void.getCPtr(pItem));
  }

  public SWIGTYPE_p_void RemoveAt(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_RemoveAt(swigCPtr, pIndex);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void RemoveLast() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_RemoveLast(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public bool RemoveIt(SWIGTYPE_p_void pItem) {
    bool ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_RemoveIt(swigCPtr, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public SWIGTYPE_p_void GetAt(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_GetAt(swigCPtr, pIndex);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void GetFirst() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_GetFirst(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void GetLast() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_GetLast(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public int Find(SWIGTYPE_p_void pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_Find(swigCPtr, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public int FindAfter(int pAfterIndex, SWIGTYPE_p_void pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_FindAfter(swigCPtr, pAfterIndex, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public int FindBefore(int pBeforeIndex, SWIGTYPE_p_void pItem) {
    int ret = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_FindBefore(swigCPtr, pBeforeIndex, SWIGTYPE_p_void.getCPtr(pItem));
    return ret;
  }

  public SWIGTYPE_p_void at(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_at(swigCPtr, pIndex);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public FbxLayerElementArray assign(SWIGTYPE_p_FbxArrayT_void_p_t pArrayTemplate) {
    FbxLayerElementArray ret = new FbxLayerElementArray(fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_assign__SWIG_0(swigCPtr, SWIGTYPE_p_FbxArrayT_void_p_t.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DirectArrayFbxVoidPtr assign(DirectArrayFbxVoidPtr pArrayTemplate) {
    DirectArrayFbxVoidPtr ret = new DirectArrayFbxVoidPtr(fbx_wrapperPINVOKE.DirectArrayFbxVoidPtr_assign__SWIG_1(swigCPtr, DirectArrayFbxVoidPtr.getCPtr(pArrayTemplate)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
