//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxAnimCurveFilterConstantKeyReducer : FbxAnimCurveFilter {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxAnimCurveFilterConstantKeyReducer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxAnimCurveFilterConstantKeyReducer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxAnimCurveFilterConstantKeyReducer() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxAnimCurveFilterConstantKeyReducer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FbxAnimCurveFilterConstantKeyReducer() : this(fbx_wrapperPINVOKE.new_FbxAnimCurveFilterConstantKeyReducer(), true) {
  }

  public override string GetName() {
    string ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_GetName(swigCPtr);
    return ret;
  }

  public override bool Apply(FbxAnimStack pAnimStack, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_0(swigCPtr, FbxAnimStack.getCPtr(pAnimStack), FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public override bool Apply(FbxAnimStack pAnimStack) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_1(swigCPtr, FbxAnimStack.getCPtr(pAnimStack));
    return ret;
  }

  public override bool Apply(FbxObject pObj, FbxAnimStack pAnimStack, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_2(swigCPtr, FbxObject.getCPtr(pObj), FbxAnimStack.getCPtr(pAnimStack), FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public override bool Apply(FbxObject pObj, FbxAnimStack pAnimStack) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_3(swigCPtr, FbxObject.getCPtr(pObj), FbxAnimStack.getCPtr(pAnimStack));
    return ret;
  }

  public override bool Apply(SWIGTYPE_p_p_FbxAnimCurve pCurve, int pCount, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_4(swigCPtr, SWIGTYPE_p_p_FbxAnimCurve.getCPtr(pCurve), pCount, FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public override bool Apply(SWIGTYPE_p_p_FbxAnimCurve pCurve, int pCount) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_5(swigCPtr, SWIGTYPE_p_p_FbxAnimCurve.getCPtr(pCurve), pCount);
    return ret;
  }

  public override bool Apply(FbxAnimCurveNode pCurveNode, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_6(swigCPtr, FbxAnimCurveNode.getCPtr(pCurveNode), FbxStatus.getCPtr(pStatus));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool Apply(FbxAnimCurveNode pCurveNode) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_7(swigCPtr, FbxAnimCurveNode.getCPtr(pCurveNode));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool Apply(FbxAnimCurve pCurve, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_8(swigCPtr, FbxAnimCurve.getCPtr(pCurve), FbxStatus.getCPtr(pStatus));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool Apply(FbxAnimCurve pCurve) {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Apply__SWIG_9(swigCPtr, FbxAnimCurve.getCPtr(pCurve));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void Reset() {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_Reset(swigCPtr);
  }

  public double GetDerivativeTolerance() {
    double ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_GetDerivativeTolerance(swigCPtr);
    return ret;
  }

  public void SetDerivativeTolerance(double pValue) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetDerivativeTolerance(swigCPtr, pValue);
  }

  public double GetValueTolerance() {
    double ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_GetValueTolerance(swigCPtr);
    return ret;
  }

  public void SetValueTolerance(double pValue) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetValueTolerance(swigCPtr, pValue);
  }

  public bool GetKeepFirstAndLastKeys() {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_GetKeepFirstAndLastKeys(swigCPtr);
    return ret;
  }

  public void SetKeepFirstAndLastKeys(bool pKeepFirstAndLastKeys) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetKeepFirstAndLastKeys(swigCPtr, pKeepFirstAndLastKeys);
  }

  public bool GetKeepOneKey() {
    bool ret = fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_GetKeepOneKey(swigCPtr);
    return ret;
  }

  public void SetKeepOneKey(bool pKeepOneKey) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetKeepOneKey(swigCPtr, pKeepOneKey);
  }

  public void SetKeepNotPureAutoKeys(bool pKeep) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetKeepNotPureAutoKeys(swigCPtr, pKeep);
  }

  public void SetTranslationThreshold(double pTranslationThreshold) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetTranslationThreshold(swigCPtr, pTranslationThreshold);
  }

  public void SetRotationThreshold(double pRotationThreshold) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetRotationThreshold(swigCPtr, pRotationThreshold);
  }

  public void SetScalingThreshold(double pScalingThreshold) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetScalingThreshold(swigCPtr, pScalingThreshold);
  }

  public void SetDefaultThreshold(double pDefaultThreshold) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetDefaultThreshold(swigCPtr, pDefaultThreshold);
  }

  public void SetModes(bool pExporting, FbxIOSettings pIOS) {
    fbx_wrapperPINVOKE.FbxAnimCurveFilterConstantKeyReducer_SetModes(swigCPtr, pExporting, FbxIOSettings.getCPtr(pIOS));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
