//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxBlendShapeChannel : FbxSubDeformer {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxBlendShapeChannel(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxBlendShapeChannel_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxBlendShapeChannel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxBlendShapeChannel_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxBlendShapeChannel Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxBlendShapeChannel ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxBlendShapeChannel(cPtr, false);
    return ret;
  }

  public new static FbxBlendShapeChannel Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxBlendShapeChannel ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxBlendShapeChannel(cPtr, false);
    return ret;
  }

  public FbxPropertyTDouble DeformPercent {
    set {
      fbx_wrapperPINVOKE.FbxBlendShapeChannel_DeformPercent_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_DeformPercent_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public bool SetBlendShapeDeformer(FbxBlendShape pBlendShape) {
    bool ret = fbx_wrapperPINVOKE.FbxBlendShapeChannel_SetBlendShapeDeformer(swigCPtr, FbxBlendShape.getCPtr(pBlendShape));
    return ret;
  }

  public FbxBlendShape GetBlendShapeDeformer() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetBlendShapeDeformer(swigCPtr);
    FbxBlendShape ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxBlendShape(cPtr, false);
    return ret;
  }

  public bool AddTargetShape(FbxShape pShape, double pFullDeformPercent) {
    bool ret = fbx_wrapperPINVOKE.FbxBlendShapeChannel_AddTargetShape__SWIG_0(swigCPtr, FbxShape.getCPtr(pShape), pFullDeformPercent);
    return ret;
  }

  public bool AddTargetShape(FbxShape pShape) {
    bool ret = fbx_wrapperPINVOKE.FbxBlendShapeChannel_AddTargetShape__SWIG_1(swigCPtr, FbxShape.getCPtr(pShape));
    return ret;
  }

  public FbxShape RemoveTargetShape(FbxShape pShape) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_RemoveTargetShape(swigCPtr, FbxShape.getCPtr(pShape));
    FbxShape ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxShape(cPtr, false);
    return ret;
  }

  public int GetTargetShapeCount() {
    int ret = fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetTargetShapeCount(swigCPtr);
    return ret;
  }

  public FbxShape GetTargetShape(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetTargetShape__SWIG_0(swigCPtr, pIndex);
    FbxShape ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxShape(cPtr, false);
    return ret;
  }

  public int GetTargetShapeIndex(FbxShape pShape) {
    int ret = fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetTargetShapeIndex(swigCPtr, FbxShape.getCPtr(pShape));
    return ret;
  }

  public SWIGTYPE_p_double GetTargetShapeFullWeights() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetTargetShapeFullWeights(swigCPtr);
    SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
    return ret;
  }

  public void SetFullWeightsCount(int pCount) {
    fbx_wrapperPINVOKE.FbxBlendShapeChannel_SetFullWeightsCount(swigCPtr, pCount);
  }

  public override FbxSubDeformer.EType GetSubDeformerType() {
    FbxSubDeformer.EType ret = (FbxSubDeformer.EType)fbx_wrapperPINVOKE.FbxBlendShapeChannel_GetSubDeformerType(swigCPtr);
    return ret;
  }

  public void Reset() {
    fbx_wrapperPINVOKE.FbxBlendShapeChannel_Reset(swigCPtr);
  }

  public override FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(fbx_wrapperPINVOKE.FbxBlendShapeChannel_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override FbxObject Clone(FbxObject.ECloneType pCloneType, FbxObject pContainer, SWIGTYPE_p_void pSet) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Clone__SWIG_0(swigCPtr, (int)pCloneType, FbxObject.getCPtr(pContainer), SWIGTYPE_p_void.getCPtr(pSet));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public override FbxObject Clone(FbxObject.ECloneType pCloneType, FbxObject pContainer) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Clone__SWIG_1(swigCPtr, (int)pCloneType, FbxObject.getCPtr(pContainer));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public override FbxObject Clone(FbxObject.ECloneType pCloneType) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Clone__SWIG_2(swigCPtr, (int)pCloneType);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public override FbxObject Clone() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxBlendShapeChannel_Clone__SWIG_3(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

}

}
