//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxConstraintParent : FbxConstraint {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxConstraintParent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxConstraintParent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxConstraintParent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxConstraintParent_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxConstraintParent Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxConstraintParent ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxConstraintParent(cPtr, false);
    return ret;
  }

  public new static FbxConstraintParent Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxConstraintParent ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxConstraintParent(cPtr, false);
    return ret;
  }

  public FbxPropertyTBool AffectTranslationX {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationX_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationX_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectTranslationY {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationY_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationY_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectTranslationZ {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationZ_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectTranslationZ_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectRotationX {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationX_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationX_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectRotationY {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationY_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationY_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectRotationZ {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationZ_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectRotationZ_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectScalingX {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingX_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingX_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectScalingY {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingY_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingY_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectScalingZ {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingZ_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_AffectScalingZ_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTReference ConstraintSources {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_ConstraintSources_set(swigCPtr, FbxPropertyTReference.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_ConstraintSources_get(swigCPtr);
      FbxPropertyTReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTReference(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTReference ConstrainedObject {
    set {
      fbx_wrapperPINVOKE.FbxConstraintParent_ConstrainedObject_set(swigCPtr, FbxPropertyTReference.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_ConstrainedObject_get(swigCPtr);
      FbxPropertyTReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTReference(cPtr, false);
      return ret;
    } 
  }

  public void SetTranslationOffset(FbxObject pObject, FbxVector4 pTranslation) {
    fbx_wrapperPINVOKE.FbxConstraintParent_SetTranslationOffset(swigCPtr, FbxObject.getCPtr(pObject), FbxVector4.getCPtr(pTranslation));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetTranslationOffset(FbxObject pObject) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxConstraintParent_GetTranslationOffset(swigCPtr, FbxObject.getCPtr(pObject)), true);
    return ret;
  }

  public virtual void SetRotationOffset(FbxObject pObject, FbxVector4 pRotation) {
    fbx_wrapperPINVOKE.FbxConstraintParent_SetRotationOffset(swigCPtr, FbxObject.getCPtr(pObject), FbxVector4.getCPtr(pRotation));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetRotationOffset(FbxObject pObject) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxConstraintParent_GetRotationOffset(swigCPtr, FbxObject.getCPtr(pObject)), true);
    return ret;
  }

  public void AddConstraintSource(FbxObject pObject, double pWeight) {
    fbx_wrapperPINVOKE.FbxConstraintParent_AddConstraintSource__SWIG_0(swigCPtr, FbxObject.getCPtr(pObject), pWeight);
  }

  public void AddConstraintSource(FbxObject pObject) {
    fbx_wrapperPINVOKE.FbxConstraintParent_AddConstraintSource__SWIG_1(swigCPtr, FbxObject.getCPtr(pObject));
  }

  public override int GetConstraintSourceCount() {
    int ret = fbx_wrapperPINVOKE.FbxConstraintParent_GetConstraintSourceCount(swigCPtr);
    return ret;
  }

  public override FbxObject GetConstraintSource(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_GetConstraintSource(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public void SetConstrainedObject(FbxObject pObject) {
    fbx_wrapperPINVOKE.FbxConstraintParent_SetConstrainedObject(swigCPtr, FbxObject.getCPtr(pObject));
  }

  public override FbxObject GetConstrainedObject() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintParent_GetConstrainedObject(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

}

}
