//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxConstraintScale : FbxConstraint {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxConstraintScale(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxConstraintScale_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxConstraintScale obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxConstraintScale_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxConstraintScale Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxConstraintScale ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxConstraintScale(cPtr, false);
    return ret;
  }

  public new static FbxConstraintScale Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxConstraintScale ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxConstraintScale(cPtr, false);
    return ret;
  }

  public FbxPropertyTBool AffectX {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_AffectX_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_AffectX_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectY {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_AffectY_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_AffectY_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool AffectZ {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_AffectZ_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_AffectZ_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble3 Scaling {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_Scaling_set(swigCPtr, FbxPropertyTDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_Scaling_get(swigCPtr);
      FbxPropertyTDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTReference ConstraintSources {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_ConstraintSources_set(swigCPtr, FbxPropertyTReference.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_ConstraintSources_get(swigCPtr);
      FbxPropertyTReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTReference(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTReference ConstrainedObject {
    set {
      fbx_wrapperPINVOKE.FbxConstraintScale_ConstrainedObject_set(swigCPtr, FbxPropertyTReference.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_ConstrainedObject_get(swigCPtr);
      FbxPropertyTReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTReference(cPtr, false);
      return ret;
    } 
  }

  public void AddConstraintSource(FbxObject pObject, double pWeight) {
    fbx_wrapperPINVOKE.FbxConstraintScale_AddConstraintSource__SWIG_0(swigCPtr, FbxObject.getCPtr(pObject), pWeight);
  }

  public void AddConstraintSource(FbxObject pObject) {
    fbx_wrapperPINVOKE.FbxConstraintScale_AddConstraintSource__SWIG_1(swigCPtr, FbxObject.getCPtr(pObject));
  }

  public override int GetConstraintSourceCount() {
    int ret = fbx_wrapperPINVOKE.FbxConstraintScale_GetConstraintSourceCount(swigCPtr);
    return ret;
  }

  public override FbxObject GetConstraintSource(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_GetConstraintSource(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public void SetConstrainedObject(FbxObject pObject) {
    fbx_wrapperPINVOKE.FbxConstraintScale_SetConstrainedObject(swigCPtr, FbxObject.getCPtr(pObject));
  }

  public override FbxObject GetConstrainedObject() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxConstraintScale_GetConstrainedObject(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

}

}
