//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxGlobalLightSettings : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxGlobalLightSettings(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxGlobalLightSettings obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void SetAmbientColor(FbxColor pAmbientColor) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetAmbientColor(swigCPtr, FbxColor.getCPtr(pAmbientColor));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxColor GetAmbientColor() {
    FbxColor ret = new FbxColor(fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetAmbientColor(swigCPtr), true);
    return ret;
  }

  public void SetFogEnable(bool pEnable) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogEnable(swigCPtr, pEnable);
  }

  public bool GetFogEnable() {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogEnable(swigCPtr);
    return ret;
  }

  public void SetFogColor(FbxColor pColor) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogColor(swigCPtr, FbxColor.getCPtr(pColor));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxColor GetFogColor() {
    FbxColor ret = new FbxColor(fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogColor(swigCPtr), true);
    return ret;
  }

  public void SetFogMode(FbxGlobalLightSettings.EFogMode pMode) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogMode(swigCPtr, (int)pMode);
  }

  public FbxGlobalLightSettings.EFogMode GetFogMode() {
    FbxGlobalLightSettings.EFogMode ret = (FbxGlobalLightSettings.EFogMode)fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogMode(swigCPtr);
    return ret;
  }

  public void SetFogDensity(double pDensity) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogDensity(swigCPtr, pDensity);
  }

  public double GetFogDensity() {
    double ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogDensity(swigCPtr);
    return ret;
  }

  public void SetFogStart(double pStart) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogStart(swigCPtr, pStart);
  }

  public double GetFogStart() {
    double ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogStart(swigCPtr);
    return ret;
  }

  public void SetFogEnd(double pEnd) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetFogEnd(swigCPtr, pEnd);
  }

  public double GetFogEnd() {
    double ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetFogEnd(swigCPtr);
    return ret;
  }

  public class ShadowPlane : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal ShadowPlane(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ShadowPlane obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~ShadowPlane() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            fbx_wrapperPINVOKE.delete_FbxGlobalLightSettings_ShadowPlane(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public ShadowPlane() : this(fbx_wrapperPINVOKE.new_FbxGlobalLightSettings_ShadowPlane(), true) {
    }
  
    public bool mEnable {
      set {
        fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mEnable_set(swigCPtr, value);
      } 
      get {
        bool ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mEnable_get(swigCPtr);
        return ret;
      } 
    }
  
    public FbxVector4 mOrigin {
      set {
        fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mOrigin_set(swigCPtr, FbxVector4.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mOrigin_get(swigCPtr);
        FbxVector4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxVector4(cPtr, false);
        return ret;
      } 
    }
  
    public FbxVector4 mNormal {
      set {
        fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mNormal_set(swigCPtr, FbxVector4.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalLightSettings_ShadowPlane_mNormal_get(swigCPtr);
        FbxVector4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxVector4(cPtr, false);
        return ret;
      } 
    }
  
  }

  public void SetShadowEnable(bool pShadowEnable) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetShadowEnable(swigCPtr, pShadowEnable);
  }

  public bool GetShadowEnable() {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetShadowEnable(swigCPtr);
    return ret;
  }

  public void SetShadowIntensity(double pShadowIntensity) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_SetShadowIntensity(swigCPtr, pShadowIntensity);
  }

  public double GetShadowIntensity() {
    double ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetShadowIntensity(swigCPtr);
    return ret;
  }

  public int GetShadowPlaneCount() {
    int ret = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetShadowPlaneCount(swigCPtr);
    return ret;
  }

  public FbxGlobalLightSettings.ShadowPlane GetShadowPlane(int pIndex, FbxStatus pStatus) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetShadowPlane__SWIG_0(swigCPtr, pIndex, FbxStatus.getCPtr(pStatus));
    FbxGlobalLightSettings.ShadowPlane ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGlobalLightSettings.ShadowPlane(cPtr, false);
    return ret;
  }

  public FbxGlobalLightSettings.ShadowPlane GetShadowPlane(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalLightSettings_GetShadowPlane__SWIG_1(swigCPtr, pIndex);
    FbxGlobalLightSettings.ShadowPlane ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxGlobalLightSettings.ShadowPlane(cPtr, false);
    return ret;
  }

  public void AddShadowPlane(FbxGlobalLightSettings.ShadowPlane pShadowPlane) {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_AddShadowPlane(swigCPtr, FbxGlobalLightSettings.ShadowPlane.getCPtr(pShadowPlane));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAllShadowPlanes() {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_RemoveAllShadowPlanes(swigCPtr);
  }

  public void RestoreDefaultSettings() {
    fbx_wrapperPINVOKE.FbxGlobalLightSettings_RestoreDefaultSettings(swigCPtr);
  }

  public FbxGlobalLightSettings assign(FbxGlobalLightSettings pGlobalLightSettings) {
    FbxGlobalLightSettings ret = new FbxGlobalLightSettings(fbx_wrapperPINVOKE.FbxGlobalLightSettings_assign(swigCPtr, FbxGlobalLightSettings.getCPtr(pGlobalLightSettings)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum EFogMode {
    eLinear,
    eExponential,
    eExponentialSquareRoot
  }

}

}
