//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxGlobalCameraSettings : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxGlobalCameraSettings(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxGlobalCameraSettings obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool SetDefaultCamera(string pCameraName, FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_SetDefaultCamera__SWIG_0(swigCPtr, pCameraName, FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public bool SetDefaultCamera(string pCameraName) {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_SetDefaultCamera__SWIG_1(swigCPtr, pCameraName);
    return ret;
  }

  public string GetDefaultCamera() {
    string ret = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetDefaultCamera(swigCPtr);
    return ret;
  }

  public void RestoreDefaultSettings() {
    fbx_wrapperPINVOKE.FbxGlobalCameraSettings_RestoreDefaultSettings(swigCPtr);
  }

  public void SetDefaultViewingMode(FbxGlobalCameraSettings.EViewingMode pViewingMode) {
    fbx_wrapperPINVOKE.FbxGlobalCameraSettings_SetDefaultViewingMode(swigCPtr, (int)pViewingMode);
  }

  public FbxGlobalCameraSettings.EViewingMode GetDefaultViewingMode() {
    FbxGlobalCameraSettings.EViewingMode ret = (FbxGlobalCameraSettings.EViewingMode)fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetDefaultViewingMode(swigCPtr);
    return ret;
  }

  public void CreateProducerCameras() {
    fbx_wrapperPINVOKE.FbxGlobalCameraSettings_CreateProducerCameras(swigCPtr);
  }

  public void DestroyProducerCameras() {
    fbx_wrapperPINVOKE.FbxGlobalCameraSettings_DestroyProducerCameras(swigCPtr);
  }

  public bool IsProducerCamera(FbxCamera pCamera) {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_IsProducerCamera(swigCPtr, FbxCamera.getCPtr(pCamera));
    return ret;
  }

  public FbxCamera GetCameraProducerPerspective() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerPerspective(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerFront() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerFront(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerBack() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerBack(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerLeft() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerLeft(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerRight() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerRight(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerTop() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerTop(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCamera GetCameraProducerBottom() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraProducerBottom(swigCPtr);
    FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCamera(cPtr, false);
    return ret;
  }

  public FbxCameraSwitcher GetCameraSwitcher() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_GetCameraSwitcher(swigCPtr);
    FbxCameraSwitcher ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCameraSwitcher(cPtr, false);
    return ret;
  }

  public void SetCameraSwitcher(FbxCameraSwitcher pSwitcher) {
    fbx_wrapperPINVOKE.FbxGlobalCameraSettings_SetCameraSwitcher(swigCPtr, FbxCameraSwitcher.getCPtr(pSwitcher));
  }

  public FbxGlobalCameraSettings assign(FbxGlobalCameraSettings pGlobalCameraSettings) {
    FbxGlobalCameraSettings ret = new FbxGlobalCameraSettings(fbx_wrapperPINVOKE.FbxGlobalCameraSettings_assign(swigCPtr, FbxGlobalCameraSettings.getCPtr(pGlobalCameraSettings)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool CopyProducerCamera(string pCameraName, FbxCamera pCamera) {
    bool ret = fbx_wrapperPINVOKE.FbxGlobalCameraSettings_CopyProducerCamera(swigCPtr, pCameraName, FbxCamera.getCPtr(pCamera));
    return ret;
  }

  public enum EViewingMode {
    eStandard,
    eXRay,
    eModelsOnly
  }

}

}
