//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxIODefaultRenderResolution : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxIODefaultRenderResolution(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxIODefaultRenderResolution obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxIODefaultRenderResolution() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxIODefaultRenderResolution(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public bool mIsOK {
    set {
      fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mIsOK_set(swigCPtr, value);
    } 
    get {
      bool ret = fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mIsOK_get(swigCPtr);
      return ret;
    } 
  }

  public FbxString mCameraName {
    set {
      fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mCameraName_set(swigCPtr, FbxString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mCameraName_get(swigCPtr);
      FbxString ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxString(cPtr, false);
      return ret;
    } 
  }

  public FbxString mResolutionMode {
    set {
      fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionMode_set(swigCPtr, FbxString.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionMode_get(swigCPtr);
      FbxString ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxString(cPtr, false);
      return ret;
    } 
  }

  public double mResolutionW {
    set {
      fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionW_set(swigCPtr, value);
    } 
    get {
      double ret = fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionW_get(swigCPtr);
      return ret;
    } 
  }

  public double mResolutionH {
    set {
      fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionH_set(swigCPtr, value);
    } 
    get {
      double ret = fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_mResolutionH_get(swigCPtr);
      return ret;
    } 
  }

  public FbxIODefaultRenderResolution() : this(fbx_wrapperPINVOKE.new_FbxIODefaultRenderResolution(), true) {
  }

  public void Reset() {
    fbx_wrapperPINVOKE.FbxIODefaultRenderResolution_Reset(swigCPtr);
  }

}

}
