//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxLayerElementTemplateFbxTexturePtr : FbxLayerElement {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxLayerElementTemplateFbxTexturePtr(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxLayerElementTemplateFbxTexturePtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DirectArrayFbxTexturePtr GetDirectArray() {
    DirectArrayFbxTexturePtr ret = new DirectArrayFbxTexturePtr(fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_GetDirectArray__SWIG_0(swigCPtr), false);
    return ret;
  }

  public DirectArrayFbxInt GetIndexArray() {
    DirectArrayFbxInt ret = new DirectArrayFbxInt(fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_GetIndexArray__SWIG_0(swigCPtr), false);
    return ret;
  }

  public override bool Clear() {
    bool ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_Clear(swigCPtr);
    return ret;
  }

  public bool eq(FbxLayerElementTemplateFbxTexturePtr pOther) {
    bool ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_eq(swigCPtr, FbxLayerElementTemplateFbxTexturePtr.getCPtr(pOther));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxLayerElementTemplateFbxTexturePtr assign(FbxLayerElementTemplateFbxTexturePtr pOther) {
    FbxLayerElementTemplateFbxTexturePtr ret = new FbxLayerElementTemplateFbxTexturePtr(fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_assign(swigCPtr, FbxLayerElementTemplateFbxTexturePtr.getCPtr(pOther)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int RemapIndexTo(FbxLayerElement.EMappingMode pNewMapping) {
    int ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_RemapIndexTo(swigCPtr, (int)pNewMapping);
    return ret;
  }

  public override int MemorySize() {
    int ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_MemorySize(swigCPtr);
    return ret;
  }

  public override bool ContentWriteTo(FbxStream pStream) {
    bool ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_ContentWriteTo(swigCPtr, FbxStream.getCPtr(pStream));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool ContentReadFrom(FbxStream pStream) {
    bool ret = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_ContentReadFrom(swigCPtr, FbxStream.getCPtr(pStream));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public DirectArrayFbxTexturePtr mDirectArray {
    set {
      fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_mDirectArray_set(swigCPtr, DirectArrayFbxTexturePtr.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_mDirectArray_get(swigCPtr);
      DirectArrayFbxTexturePtr ret = (cPtr == global::System.IntPtr.Zero) ? null : new DirectArrayFbxTexturePtr(cPtr, false);
      return ret;
    } 
  }

  public DirectArrayFbxInt mIndexArray {
    set {
      fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_mIndexArray_set(swigCPtr, DirectArrayFbxInt.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLayerElementTemplateFbxTexturePtr_mIndexArray_get(swigCPtr);
      DirectArrayFbxInt ret = (cPtr == global::System.IntPtr.Zero) ? null : new DirectArrayFbxInt(cPtr, false);
      return ret;
    } 
  }

}

}
