//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxLight : FbxNodeAttribute {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxLight(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxLight_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxLight obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxLight_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxLight_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxLight Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxLight ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLight(cPtr, false);
    return ret;
  }

  public new static FbxLight Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxLight ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxLight(cPtr, false);
    return ret;
  }

  public void SetShadowTexture(FbxTexture pTexture) {
    fbx_wrapperPINVOKE.FbxLight_SetShadowTexture(swigCPtr, FbxTexture.getCPtr(pTexture));
  }

  public FbxTexture GetShadowTexture() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_GetShadowTexture(swigCPtr);
    FbxTexture ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxTexture(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxLight__EType_t LightType {
    set {
      fbx_wrapperPINVOKE.FbxLight_LightType_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxLight__EType_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_LightType_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxLight__EType_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxLight__EType_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool CastLight {
    set {
      fbx_wrapperPINVOKE.FbxLight_CastLight_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_CastLight_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool DrawVolumetricLight {
    set {
      fbx_wrapperPINVOKE.FbxLight_DrawVolumetricLight_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_DrawVolumetricLight_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool DrawGroundProjection {
    set {
      fbx_wrapperPINVOKE.FbxLight_DrawGroundProjection_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_DrawGroundProjection_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool DrawFrontFacingVolumetricLight {
    set {
      fbx_wrapperPINVOKE.FbxLight_DrawFrontFacingVolumetricLight_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_DrawFrontFacingVolumetricLight_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble3 Color {
    set {
      fbx_wrapperPINVOKE.FbxLight_Color_set(swigCPtr, FbxPropertyTDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_Color_get(swigCPtr);
      FbxPropertyTDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble Intensity {
    set {
      fbx_wrapperPINVOKE.FbxLight_Intensity_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_Intensity_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble InnerAngle {
    set {
      fbx_wrapperPINVOKE.FbxLight_InnerAngle_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_InnerAngle_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble OuterAngle {
    set {
      fbx_wrapperPINVOKE.FbxLight_OuterAngle_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_OuterAngle_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble Fog {
    set {
      fbx_wrapperPINVOKE.FbxLight_Fog_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_Fog_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxLight__EDecayType_t DecayType {
    set {
      fbx_wrapperPINVOKE.FbxLight_DecayType_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxLight__EDecayType_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_DecayType_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxLight__EDecayType_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxLight__EDecayType_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble DecayStart {
    set {
      fbx_wrapperPINVOKE.FbxLight_DecayStart_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_DecayStart_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t FileName {
    set {
      fbx_wrapperPINVOKE.FbxLight_FileName_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_FileName_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool EnableNearAttenuation {
    set {
      fbx_wrapperPINVOKE.FbxLight_EnableNearAttenuation_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_EnableNearAttenuation_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble NearAttenuationStart {
    set {
      fbx_wrapperPINVOKE.FbxLight_NearAttenuationStart_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_NearAttenuationStart_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble NearAttenuationEnd {
    set {
      fbx_wrapperPINVOKE.FbxLight_NearAttenuationEnd_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_NearAttenuationEnd_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool EnableFarAttenuation {
    set {
      fbx_wrapperPINVOKE.FbxLight_EnableFarAttenuation_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_EnableFarAttenuation_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble FarAttenuationStart {
    set {
      fbx_wrapperPINVOKE.FbxLight_FarAttenuationStart_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_FarAttenuationStart_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble FarAttenuationEnd {
    set {
      fbx_wrapperPINVOKE.FbxLight_FarAttenuationEnd_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_FarAttenuationEnd_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool CastShadows {
    set {
      fbx_wrapperPINVOKE.FbxLight_CastShadows_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_CastShadows_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble3 ShadowColor {
    set {
      fbx_wrapperPINVOKE.FbxLight_ShadowColor_set(swigCPtr, FbxPropertyTDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_ShadowColor_get(swigCPtr);
      FbxPropertyTDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble3(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxLight__EAreaLightShape_t AreaLightShape {
    set {
      fbx_wrapperPINVOKE.FbxLight_AreaLightShape_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxLight__EAreaLightShape_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_AreaLightShape_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxLight__EAreaLightShape_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxLight__EAreaLightShape_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_float_t LeftBarnDoor {
    set {
      fbx_wrapperPINVOKE.FbxLight_LeftBarnDoor_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_LeftBarnDoor_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_float_t RightBarnDoor {
    set {
      fbx_wrapperPINVOKE.FbxLight_RightBarnDoor_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_RightBarnDoor_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_float_t TopBarnDoor {
    set {
      fbx_wrapperPINVOKE.FbxLight_TopBarnDoor_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_TopBarnDoor_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_float_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_float_t BottomBarnDoor {
    set {
      fbx_wrapperPINVOKE.FbxLight_BottomBarnDoor_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_float_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_BottomBarnDoor_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_float_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_float_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool EnableBarnDoor {
    set {
      fbx_wrapperPINVOKE.FbxLight_EnableBarnDoor_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxLight_EnableBarnDoor_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public override FbxNodeAttribute.EType GetAttributeType() {
    FbxNodeAttribute.EType ret = (FbxNodeAttribute.EType)fbx_wrapperPINVOKE.FbxLight_GetAttributeType(swigCPtr);
    return ret;
  }

  public enum EType {
    ePoint,
    eDirectional,
    eSpot,
    eArea,
    eVolume
  }

  public enum EDecayType {
    eNone,
    eLinear,
    eQuadratic,
    eCubic
  }

  public enum EAreaLightShape {
    eRectangle,
    eSphere
  }

}

}
