//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxMarker : FbxNodeAttribute {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxMarker(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxMarker_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxMarker obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxMarker_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxMarker_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxMarker Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxMarker ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxMarker(cPtr, false);
    return ret;
  }

  public new static FbxMarker Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxMarker ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxMarker(cPtr, false);
    return ret;
  }

  public override FbxNodeAttribute.EType GetAttributeType() {
    FbxNodeAttribute.EType ret = (FbxNodeAttribute.EType)fbx_wrapperPINVOKE.FbxMarker_GetAttributeType(swigCPtr);
    return ret;
  }

  public void Reset() {
    fbx_wrapperPINVOKE.FbxMarker_Reset(swigCPtr);
  }

  public void SetType(FbxMarker.EType pType) {
    fbx_wrapperPINVOKE.FbxMarker_SetType(swigCPtr, (int)pType);
  }

  public FbxMarker.EType GetType() {
    FbxMarker.EType ret = (FbxMarker.EType)fbx_wrapperPINVOKE.FbxMarker_GetType(swigCPtr);
    return ret;
  }

  public double GetDefaultOcclusion() {
    double ret = fbx_wrapperPINVOKE.FbxMarker_GetDefaultOcclusion(swigCPtr);
    return ret;
  }

  public void SetDefaultOcclusion(double pOcclusion) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultOcclusion(swigCPtr, pOcclusion);
  }

  public double GetDefaultIKReachTranslation() {
    double ret = fbx_wrapperPINVOKE.FbxMarker_GetDefaultIKReachTranslation(swigCPtr);
    return ret;
  }

  public void SetDefaultIKReachTranslation(double pIKReachTranslation) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultIKReachTranslation(swigCPtr, pIKReachTranslation);
  }

  public double GetDefaultIKReachRotation() {
    double ret = fbx_wrapperPINVOKE.FbxMarker_GetDefaultIKReachRotation(swigCPtr);
    return ret;
  }

  public void SetDefaultIKReachRotation(double pIKReachRotation) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultIKReachRotation(swigCPtr, pIKReachRotation);
  }

  public double GetDefaultIKPull() {
    double ret = fbx_wrapperPINVOKE.FbxMarker_GetDefaultIKPull(swigCPtr);
    return ret;
  }

  public void SetDefaultIKPull(double pIKPull) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultIKPull(swigCPtr, pIKPull);
  }

  public double GetDefaultIKPullHips() {
    double ret = fbx_wrapperPINVOKE.FbxMarker_GetDefaultIKPullHips(swigCPtr);
    return ret;
  }

  public void SetDefaultIKPullHips(double pIKPullHips) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultIKPullHips(swigCPtr, pIKPullHips);
  }

  public FbxColor GetDefaultColor(FbxColor pColor) {
    FbxColor ret = new FbxColor(fbx_wrapperPINVOKE.FbxMarker_GetDefaultColor(swigCPtr, FbxColor.getCPtr(pColor)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetDefaultColor(FbxColor pColor) {
    fbx_wrapperPINVOKE.FbxMarker_SetDefaultColor(swigCPtr, FbxColor.getCPtr(pColor));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxMarker__ELook_t Look {
    set {
      fbx_wrapperPINVOKE.FbxMarker_Look_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxMarker__ELook_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_Look_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxMarker__ELook_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxMarker__ELook_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool DrawLink {
    set {
      fbx_wrapperPINVOKE.FbxMarker_DrawLink_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_DrawLink_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble Size {
    set {
      fbx_wrapperPINVOKE.FbxMarker_Size_set(swigCPtr, FbxPropertyTDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_Size_get(swigCPtr);
      FbxPropertyTDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool ShowLabel {
    set {
      fbx_wrapperPINVOKE.FbxMarker_ShowLabel_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_ShowLabel_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTDouble3 IKPivot {
    set {
      fbx_wrapperPINVOKE.FbxMarker_IKPivot_set(swigCPtr, FbxPropertyTDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxMarker_IKPivot_get(swigCPtr);
      FbxPropertyTDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxProperty GetOcclusion() {
    FbxProperty ret = new FbxProperty(fbx_wrapperPINVOKE.FbxMarker_GetOcclusion(swigCPtr), true);
    return ret;
  }

  public FbxProperty GetIKReachTranslation() {
    FbxProperty ret = new FbxProperty(fbx_wrapperPINVOKE.FbxMarker_GetIKReachTranslation(swigCPtr), true);
    return ret;
  }

  public FbxProperty GetIKReachRotation() {
    FbxProperty ret = new FbxProperty(fbx_wrapperPINVOKE.FbxMarker_GetIKReachRotation(swigCPtr), true);
    return ret;
  }

  public FbxProperty GetIKPull() {
    FbxProperty ret = new FbxProperty(fbx_wrapperPINVOKE.FbxMarker_GetIKPull(swigCPtr), true);
    return ret;
  }

  public FbxProperty GetIKPullHips() {
    FbxProperty ret = new FbxProperty(fbx_wrapperPINVOKE.FbxMarker_GetIKPullHips(swigCPtr), true);
    return ret;
  }

  public override FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(fbx_wrapperPINVOKE.FbxMarker_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum EType {
    eStandard,
    eOptical,
    eEffectorFK,
    eEffectorIK
  }

  public enum ELook {
    eCube,
    eHardCross,
    eLightCross,
    eSphere,
    eCapsule,
    eBox,
    eBone,
    eCircle,
    eSquare,
    eStick,
    eNone
  }

}

}
