//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxOperatorEntryView : FbxEntryView {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxOperatorEntryView(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxOperatorEntryView_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxOperatorEntryView obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxOperatorEntryView() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxOperatorEntryView(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static string sEntryType {
    set {
      fbx_wrapperPINVOKE.FbxOperatorEntryView_sEntryType_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxOperatorEntryView_sEntryType_get();
      return ret;
    } 
  }

  public FbxOperatorEntryView(FbxBindingTableEntry pEntry, bool pAsSource, bool pCreate) : this(fbx_wrapperPINVOKE.new_FbxOperatorEntryView__SWIG_0(FbxBindingTableEntry.getCPtr(pEntry), pAsSource, pCreate), true) {
  }

  public FbxOperatorEntryView(FbxBindingTableEntry pEntry, bool pAsSource) : this(fbx_wrapperPINVOKE.new_FbxOperatorEntryView__SWIG_1(FbxBindingTableEntry.getCPtr(pEntry), pAsSource), true) {
  }

  public string GetOperatorName() {
    string ret = fbx_wrapperPINVOKE.FbxOperatorEntryView_GetOperatorName(swigCPtr);
    return ret;
  }

  public void SetOperatorName(string pName) {
    fbx_wrapperPINVOKE.FbxOperatorEntryView_SetOperatorName(swigCPtr, pName);
  }

  public override string EntryType() {
    string ret = fbx_wrapperPINVOKE.FbxOperatorEntryView_EntryType(swigCPtr);
    return ret;
  }

}

}
