//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxPlugin : FbxListener {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxPlugin(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxPlugin_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxPlugin obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public SWIGTYPE_p_FbxListNodeT_FbxPlugin_t GetListNode(int index) {
    SWIGTYPE_p_FbxListNodeT_FbxPlugin_t ret = new SWIGTYPE_p_FbxListNodeT_FbxPlugin_t(fbx_wrapperPINVOKE.FbxPlugin_GetListNode__SWIG_0(swigCPtr, index), false);
    return ret;
  }

  public SWIGTYPE_p_FbxListNodeT_FbxPlugin_t GetListNode() {
    SWIGTYPE_p_FbxListNodeT_FbxPlugin_t ret = new SWIGTYPE_p_FbxListNodeT_FbxPlugin_t(fbx_wrapperPINVOKE.FbxPlugin_GetListNode__SWIG_1(swigCPtr), false);
    return ret;
  }

  public virtual bool SpecificInitialize() {
    bool ret = fbx_wrapperPINVOKE.FbxPlugin_SpecificInitialize(swigCPtr);
    return ret;
  }

  public virtual bool SpecificTerminate() {
    bool ret = fbx_wrapperPINVOKE.FbxPlugin_SpecificTerminate(swigCPtr);
    return ret;
  }

  public virtual void WriteBegin(FbxScene pScene) {
    fbx_wrapperPINVOKE.FbxPlugin_WriteBegin(swigCPtr, FbxScene.getCPtr(pScene));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void WriteParameters(FbxObject pParams) {
    fbx_wrapperPINVOKE.FbxPlugin_WriteParameters(swigCPtr, FbxObject.getCPtr(pParams));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void WriteEnd(FbxScene pScene) {
    fbx_wrapperPINVOKE.FbxPlugin_WriteEnd(swigCPtr, FbxScene.getCPtr(pScene));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ReadBegin(FbxScene pScene) {
    fbx_wrapperPINVOKE.FbxPlugin_ReadBegin(swigCPtr, FbxScene.getCPtr(pScene));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ReadParameters(FbxObject pParams) {
    fbx_wrapperPINVOKE.FbxPlugin_ReadParameters(swigCPtr, FbxObject.getCPtr(pParams));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void ReadEnd(FbxScene pScene) {
    fbx_wrapperPINVOKE.FbxPlugin_ReadEnd(swigCPtr, FbxScene.getCPtr(pScene));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxPluginDef GetDefinition() {
    FbxPluginDef ret = new FbxPluginDef(fbx_wrapperPINVOKE.FbxPlugin_GetDefinition(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_void GetModuleHdl() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxPlugin_GetModuleHdl(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public FbxObject GetPluginSettings() {
    FbxObject ret = new FbxObject(fbx_wrapperPINVOKE.FbxPlugin_GetPluginSettings__SWIG_0(swigCPtr), false);
    return ret;
  }

  public virtual void Destroy() {
    fbx_wrapperPINVOKE.FbxPlugin_Destroy(swigCPtr);
  }

}

}
