//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxQuaternion : FbxDouble4 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxQuaternion(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxQuaternion_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxQuaternion obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxQuaternion() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxQuaternion(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FbxQuaternion() : this(fbx_wrapperPINVOKE.new_FbxQuaternion__SWIG_0(), true) {
  }

  public FbxQuaternion(FbxQuaternion pV) : this(fbx_wrapperPINVOKE.new_FbxQuaternion__SWIG_1(FbxQuaternion.getCPtr(pV)), true) {
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxQuaternion(double pX, double pY, double pZ, double pW) : this(fbx_wrapperPINVOKE.new_FbxQuaternion__SWIG_2(pX, pY, pZ, pW), true) {
  }

  public FbxQuaternion(double pX, double pY, double pZ) : this(fbx_wrapperPINVOKE.new_FbxQuaternion__SWIG_3(pX, pY, pZ), true) {
  }

  public FbxQuaternion(FbxVector4 pAxis, double pDegree) : this(fbx_wrapperPINVOKE.new_FbxQuaternion__SWIG_4(FbxVector4.getCPtr(pAxis), pDegree), true) {
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxQuaternion assign(FbxQuaternion pQuaternion) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_assign(swigCPtr, FbxQuaternion.getCPtr(pQuaternion)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new SWIGTYPE_p_double at(int pIndex) {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(fbx_wrapperPINVOKE.FbxQuaternion_at__SWIG_0(swigCPtr, pIndex), false);
    return ret;
  }

  public double GetAt(int pIndex) {
    double ret = fbx_wrapperPINVOKE.FbxQuaternion_GetAt(swigCPtr, pIndex);
    return ret;
  }

  public void SetAt(int pIndex, double pValue) {
    fbx_wrapperPINVOKE.FbxQuaternion_SetAt(swigCPtr, pIndex, pValue);
  }

  public void Set(double pX, double pY, double pZ, double pW) {
    fbx_wrapperPINVOKE.FbxQuaternion_Set__SWIG_0(swigCPtr, pX, pY, pZ, pW);
  }

  public void Set(double pX, double pY, double pZ) {
    fbx_wrapperPINVOKE.FbxQuaternion_Set__SWIG_1(swigCPtr, pX, pY, pZ);
  }

  public FbxQuaternion add(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_add__SWIG_0(swigCPtr, pValue), true);
    return ret;
  }

  public FbxQuaternion sub(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_sub__SWIG_0(swigCPtr, pValue), true);
    return ret;
  }

  public FbxQuaternion mul(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_mul__SWIG_0(swigCPtr, pValue), true);
    return ret;
  }

  public FbxQuaternion div(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_div__SWIG_0(swigCPtr, pValue), true);
    return ret;
  }

  public FbxQuaternion add_assign(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_add_assign__SWIG_0(swigCPtr, pValue), false);
    return ret;
  }

  public FbxQuaternion sub_assign(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_sub_assign__SWIG_0(swigCPtr, pValue), false);
    return ret;
  }

  public FbxQuaternion mul_assign(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_mul_assign__SWIG_0(swigCPtr, pValue), false);
    return ret;
  }

  public FbxQuaternion div_assign(double pValue) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_div_assign__SWIG_0(swigCPtr, pValue), false);
    return ret;
  }

  public FbxQuaternion neg() {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_neg(swigCPtr), true);
    return ret;
  }

  public FbxQuaternion add(FbxQuaternion pQuaternion) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_add__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pQuaternion)), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion sub(FbxQuaternion pQuaternion) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_sub__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pQuaternion)), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion mul(FbxQuaternion pOther) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_mul__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pOther)), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion div(FbxQuaternion pOther) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_div__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pOther)), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion add_assign(FbxQuaternion pQuaternion) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_add_assign__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pQuaternion)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion sub_assign(FbxQuaternion pQuaternion) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_sub_assign__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pQuaternion)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion mul_assign(FbxQuaternion pOther) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_mul_assign__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pOther)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion div_assign(FbxQuaternion pOther) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_div_assign__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pOther)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxQuaternion Product(FbxQuaternion pOther) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_Product(swigCPtr, FbxQuaternion.getCPtr(pOther)), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double DotProduct(FbxQuaternion pQuaternion) {
    double ret = fbx_wrapperPINVOKE.FbxQuaternion_DotProduct(swigCPtr, FbxQuaternion.getCPtr(pQuaternion));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Normalize() {
    fbx_wrapperPINVOKE.FbxQuaternion_Normalize(swigCPtr);
  }

  public void Conjugate() {
    fbx_wrapperPINVOKE.FbxQuaternion_Conjugate(swigCPtr);
  }

  public double Length() {
    double ret = fbx_wrapperPINVOKE.FbxQuaternion_Length(swigCPtr);
    return ret;
  }

  public void Inverse() {
    fbx_wrapperPINVOKE.FbxQuaternion_Inverse(swigCPtr);
  }

  public void SetAxisAngle(FbxVector4 pAxis, double pDegree) {
    fbx_wrapperPINVOKE.FbxQuaternion_SetAxisAngle(swigCPtr, FbxVector4.getCPtr(pAxis), pDegree);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxQuaternion Slerp(FbxQuaternion pOther, double pWeight) {
    FbxQuaternion ret = new FbxQuaternion(fbx_wrapperPINVOKE.FbxQuaternion_Slerp(swigCPtr, FbxQuaternion.getCPtr(pOther), pWeight), true);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void ComposeSphericalXYZ(FbxVector4 pEuler) {
    fbx_wrapperPINVOKE.FbxQuaternion_ComposeSphericalXYZ(swigCPtr, FbxVector4.getCPtr(pEuler));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 DecomposeSphericalXYZ() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxQuaternion_DecomposeSphericalXYZ(swigCPtr), true);
    return ret;
  }

  public bool eq(FbxQuaternion pV) {
    bool ret = fbx_wrapperPINVOKE.FbxQuaternion_eq(swigCPtr, FbxQuaternion.getCPtr(pV));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ne(FbxQuaternion pV) {
    bool ret = fbx_wrapperPINVOKE.FbxQuaternion_ne(swigCPtr, FbxQuaternion.getCPtr(pV));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Compare(FbxQuaternion pQ2, double pThreshold) {
    int ret = fbx_wrapperPINVOKE.FbxQuaternion_Compare__SWIG_0(swigCPtr, FbxQuaternion.getCPtr(pQ2), pThreshold);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int Compare(FbxQuaternion pQ2) {
    int ret = fbx_wrapperPINVOKE.FbxQuaternion_Compare__SWIG_1(swigCPtr, FbxQuaternion.getCPtr(pQ2));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void GetQuaternionFromPositionToPosition(FbxVector4 pP0, FbxVector4 pP1) {
    fbx_wrapperPINVOKE.FbxQuaternion_GetQuaternionFromPositionToPosition(swigCPtr, FbxVector4.getCPtr(pP0), FbxVector4.getCPtr(pP1));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
