//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxSurfaceMaterial : FbxObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxSurfaceMaterial(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxSurfaceMaterial_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxSurfaceMaterial obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_ClassId_set(FbxClassId.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxSurfaceMaterial_ClassId_get();
      FbxClassId ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxClassId(cPtr, false);
      return ret;
    } 
  }

  public override FbxClassId GetClassId() {
    FbxClassId ret = new FbxClassId(fbx_wrapperPINVOKE.FbxSurfaceMaterial_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxSurfaceMaterial Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxSurfaceMaterial_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxSurfaceMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxSurfaceMaterial(cPtr, false);
    return ret;
  }

  public new static FbxSurfaceMaterial Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxSurfaceMaterial_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxSurfaceMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxSurfaceMaterial(cPtr, false);
    return ret;
  }

  public static string sShadingModel {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShadingModel_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShadingModel_get();
      return ret;
    } 
  }

  public static string sMultiLayer {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sMultiLayer_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sMultiLayer_get();
      return ret;
    } 
  }

  public static string sEmissive {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sEmissive_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sEmissive_get();
      return ret;
    } 
  }

  public static string sEmissiveFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sEmissiveFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sEmissiveFactor_get();
      return ret;
    } 
  }

  public static string sAmbient {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sAmbient_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sAmbient_get();
      return ret;
    } 
  }

  public static string sAmbientFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sAmbientFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sAmbientFactor_get();
      return ret;
    } 
  }

  public static string sDiffuse {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDiffuse_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDiffuse_get();
      return ret;
    } 
  }

  public static string sDiffuseFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDiffuseFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDiffuseFactor_get();
      return ret;
    } 
  }

  public static string sSpecular {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sSpecular_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sSpecular_get();
      return ret;
    } 
  }

  public static string sSpecularFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sSpecularFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sSpecularFactor_get();
      return ret;
    } 
  }

  public static string sShininess {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShininess_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShininess_get();
      return ret;
    } 
  }

  public static string sBump {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sBump_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sBump_get();
      return ret;
    } 
  }

  public static string sNormalMap {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sNormalMap_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sNormalMap_get();
      return ret;
    } 
  }

  public static string sBumpFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sBumpFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sBumpFactor_get();
      return ret;
    } 
  }

  public static string sTransparentColor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sTransparentColor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sTransparentColor_get();
      return ret;
    } 
  }

  public static string sTransparencyFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sTransparencyFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sTransparencyFactor_get();
      return ret;
    } 
  }

  public static string sReflection {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sReflection_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sReflection_get();
      return ret;
    } 
  }

  public static string sReflectionFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sReflectionFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sReflectionFactor_get();
      return ret;
    } 
  }

  public static string sDisplacementColor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDisplacementColor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDisplacementColor_get();
      return ret;
    } 
  }

  public static string sDisplacementFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDisplacementFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sDisplacementFactor_get();
      return ret;
    } 
  }

  public static string sVectorDisplacementColor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sVectorDisplacementColor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sVectorDisplacementColor_get();
      return ret;
    } 
  }

  public static string sVectorDisplacementFactor {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sVectorDisplacementFactor_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sVectorDisplacementFactor_get();
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ShadingModel {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_ShadingModel_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxSurfaceMaterial_ShadingModel_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyTBool MultiLayer {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_MultiLayer_set(swigCPtr, FbxPropertyTBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxSurfaceMaterial_MultiLayer_get(swigCPtr);
      FbxPropertyTBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyTBool(cPtr, false);
      return ret;
    } 
  }

  public static bool sMultiLayerDefault {
    get {
      bool ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sMultiLayerDefault_get();
      return ret;
    } 
  }

  public static string sShadingModelDefault {
    set {
      fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShadingModelDefault_set(value);
    } 
    get {
      string ret = fbx_wrapperPINVOKE.FbxSurfaceMaterial_sShadingModelDefault_get();
      return ret;
    } 
  }

}

}
